package tom.mapping.introspectors.algebra;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EClass;

import tom.library.sl.Introspector;
import tom.mapping.IntrospectorManager;

import org.polymodel.algebra.AlgebraPackage;

import org.polymodel.scop.*; 
import org.polymodel.scop.util.*;
import org.polymodel.scop.annotation.*; 
import org.polymodel.scop.annotation.util.*;
import org.polymodel.algebra.*; 
import org.polymodel.algebra.util.*;
import org.polymodel.algebra.affine.*; 
import org.polymodel.algebra.affine.util.*;
import org.polymodel.algebra.quasiAffine.*; 
import org.polymodel.algebra.quasiAffine.util.*;
import org.polymodel.algebra.polynomials.*; 
import org.polymodel.algebra.polynomials.util.*;
import org.polymodel.algebra.reductions.*; 
import org.polymodel.algebra.reductions.util.*;

/* PROTECTED REGION ID(introspector_imports) ENABLED START */
// protected imports
/* PROTECTED REGION END */

/**
* TOM introspector for scop.
* -- Autogenerated by TOM mapping EMF genrator --
*/

public class AlgebraIntrospector implements Introspector {
	
	public static final AlgebraIntrospector INSTANCE = new AlgebraIntrospector();
	
	static {
		IntrospectorManager.INSTANCE.register(AlgebraPackage.eINSTANCE, INSTANCE);
	}

	/* PROTECTED REGION ID(introspector_members) ENABLED START */
	/* PROTECTED REGION END */
	
	protected AlgebraIntrospector() {}
	
	public Object getChildAt(Object o, int i) {
		return getChildren(o)[i];
	}
	
	public int getChildCount(Object o) {
		return getChildren(o).length;
	}
	
	@SuppressWarnings("unchecked")
	public Object[] getChildren(Object arg0) {
		List<Object> l = new ArrayList<Object>();
		if (arg0 instanceof List) {
			// Children of a list are its content
			for(Object object : (List<Object>) arg0) {
				l.add(object);
			}
			return l.toArray();
		}
		return AlgebraChildrenGetter.INSTANCE.children(arg0);
	}
	
	private static class AlgebraChildrenGetter extends AlgebraSwitch<Object[]> {
		public final static AlgebraChildrenGetter INSTANCE = new AlgebraChildrenGetter();
		
		private AlgebraChildrenGetter(){}
		
		public Object[] children(Object i) {
			Object[] children = doSwitch((EObject) i);
			return children != null ? children : new Object[0];
		}
		
		public Object[] caseIntConstraint(IntConstraint o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getLhs() != null)
				l.add(o.getLhs());
			if (o.getRhs() != null)
				l.add(o.getRhs());
			
			/*PROTECTED REGION ID(getter_algebra_IntConstraint) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseCompositeIntExpression(CompositeIntExpression o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getLeft() != null)
				l.add(o.getLeft());
			if (o.getRight() != null)
				l.add(o.getRight());
			
			/*PROTECTED REGION ID(getter_algebra_CompositeIntExpression) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseSelectExpression(SelectExpression o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getCondition() != null)
				l.add(o.getCondition());
			if (o.getThen() != null)
				l.add(o.getThen());
			if (o.getElse() != null)
				l.add(o.getElse());
			
			/*PROTECTED REGION ID(getter_algebra_SelectExpression) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
	}
	
	@SuppressWarnings("unchecked")
	public <T> T setChildren(T arg0, Object[] arg1) {
		if (arg0 instanceof List) {
			// If object is a list then content of the original list has to be replaced
			List<Object> list = (List<Object>) arg0;
			list.clear();
			for (int i = 0; i < arg1.length; i++) {
				list.add(arg1[i]);
			}
			return arg0;
		} else {
			return (T) AlgebraChildrenSetter.INSTANCE.set(arg0, arg1);
		}
	}
	
	private static class AlgebraChildrenSetter extends AlgebraSwitch<Object> {
		public final static AlgebraChildrenSetter INSTANCE = new AlgebraChildrenSetter();
		
		private Object[] children;
		private AlgebraChildrenSetter(){}
		
		public Object set(Object i, Object[] children) {
			this.children = children;
			return doSwitch((EObject) i);
		}
		
		public Object caseIntConstraint(IntConstraint o) {
			o.setLhs((IntExpression)children[0]);
			o.setRhs((IntExpression)children[1]);
		
			/*PROTECTED REGION ID(setter_algebra_IntConstraint) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
		
		public Object caseCompositeIntExpression(CompositeIntExpression o) {
			o.setLeft((IntExpression)children[0]);
			o.setRight((IntExpression)children[1]);
		
			/*PROTECTED REGION ID(setter_algebra_CompositeIntExpression) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
		
		public Object caseSelectExpression(SelectExpression o) {
			o.setThen((IntExpression)children[0]);
			o.setElse((IntExpression)children[1]);
		
			/*PROTECTED REGION ID(setter_algebra_SelectExpression) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
	}

	public <T> T setChildAt(T o, int i, Object obj) {
		throw new RuntimeException("Not implemented");
	}
}
