affine Jacobi1D {Nb,Tb,Nl,Tl,b|Tl==0 && Nl==0 && Nb>=1 && b>=3 && Tb>=0}
input
	double A_bl {iBl,iLoc|Tl==0 && Nl==0 && iBl>=0 && iLoc>=0 && b>=iLoc+1 && b>=3 && Nb>=iBl+1 && Nb>=1 && Tb>=0};
output
	double B_bl {iBl,iLoc|Tl==0 && Nl==0 && iBl>=0 && iLoc>=0 && b>=iLoc+1 && b>=3 && Nb>=iBl+1 && Nb>=1 && Tb>=0};
local
	double temp_bl {iBl,tBl,iLoc,tLoc|tBl==iBl && Tl==0 && Nl==0 && Nb>=1 && b>=3 && iBl>=0 && Tb>=iBl+1 && b>=iLoc+1 && tLoc>=0 && iLoc>=tLoc}
		|| {iBl,tBl,iLoc,tLoc|tBl+Nb==iBl && Tl==0 && Nl==0 && Nb>=1 && b>=3 && iBl>=Nb && Nb+Tb>=iBl+1 && iLoc>=0 && tLoc>=iLoc+1 && b>=tLoc+1}
		|| {iBl,tBl,iLoc,tLoc|tLoc==0 && tBl==Tb && Tl==0 && Nl==0 && Tb>=0 && b>=3 && iBl>=Tb && Nb+Tb>=iBl+1 && iLoc>=0 && b>=iLoc+1}
		|| {iBl,tBl,iLoc,tLoc|Tl==0 && Nl==0 && b>=3 && tBl>=0 && iBl>=tBl+1 && Tb>=tBl+1 && tBl+Nb>=iBl+1 && iLoc>=0 && b>=iLoc+1 && tLoc>=0 && b>=tLoc+1};
let
temp_bl[iBl,tBl,iLoc,tLoc] = case
	{|tBl==0 && iBl==0 && Nb>=1 && Tb>=0} : case
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=0 && b>=3 && b>=iLoc+1} : A_bl[iBl-tBl,iLoc-tLoc];
		{|tLoc==iLoc && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+1} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|Tl==0 && Nl==0 && tLoc>=1 && iLoc>=2 && b>=3 && b>=iLoc+1 && b>=tLoc+1 && iLoc>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==0 && iBl==Nb && Nb>=1 && Tb>=0} : case
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=0 && b>=3 && b>=iLoc+1} : A_bl[iBl-tBl,iLoc-tLoc];
		{|tLoc==1 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1];
		{|tLoc==iLoc+1 && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+2} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|iLoc==0 && Tl==0 && Nl==0 && tLoc>=1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && tLoc>=1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && tLoc>=1 && iLoc>=2 && b>=3 && b>=iLoc+1 && b>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==0 && Nb>=iBl+1 && Tb>=0 && iBl>=1 && Nb>=1} : case
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=0 && b>=3 && b>=iLoc+1} : A_bl[iBl-tBl,iLoc-tLoc];
		{|iLoc==0 && Tl==0 && Nl==0 && tLoc>=1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && tLoc>=1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && tLoc>=1 && iLoc>=2 && b>=3 && b>=iLoc+1 && b>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==1 && iBl==1 && Nb==1 && Tb>=0} : case
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1];
		{|tLoc==iLoc && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+1} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|tLoc==0 && iLoc==b-1 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1];
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3 && iLoc>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==iBl && Nb==1 && iBl>=2 && Tb>=0} : case
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1];
		{|tLoc==iLoc && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+1} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|tLoc==0 && iLoc==b-1 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1];
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3 && iLoc>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==iBl && Nb>=2 && Tb>=0 && iBl>=2} : case
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1];
		{|tLoc==iLoc && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+1} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3 && iLoc>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==1 && iBl==1 && Nb>=2 && Tb>=0} : case
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1];
		{|tLoc==iLoc && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+1} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3 && iLoc>=tLoc+1} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|Nb+tBl==iBl && iBl>=Nb+1 && Nb>=1 && Tb>=0} : case
		{|tLoc==1 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1];
		{|tLoc==iLoc+1 && Tl==0 && Nl==0 && b>=3 && iLoc>=1 && b>=iLoc+2} : temp_bl[iBl,tBl,iLoc-1,tLoc-1];
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|iLoc==0 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|tBl==1 && iBl==Nb && Nb>=2 && Tb>=0} : case
		{|tLoc==0 && iLoc==b-1 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1];
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|iLoc==0 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|Nb+tBl==iBl+1 && Nb>=2 && Tb>=0 && iBl>=Nb+1} : case
		{|tLoc==0 && iLoc==b-1 && Tl==0 && Nl==0 && b>=3} : temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1];
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|iLoc==0 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;

	{|Tb>=0 && tBl>=1 && iBl>=tBl+1 && Nb+tBl>=iBl+2 && Nb>=1} : case
		{|tLoc==0 && iLoc==0 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl-1,tBl-1,b+iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && iLoc==1 && Tl==0 && Nl==0 && b>=3} : (((temp_bl[iBl-1,tBl-1,b+iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|tLoc==0 && Tl==0 && Nl==0 && iLoc>=2 && b>=3 && b>=iLoc+1} : (((temp_bl[iBl,tBl-1,iLoc-2,b+tLoc-1] + temp_bl[iBl,tBl-1,iLoc-1,b+tLoc-1]) + temp_bl[iBl,tBl-1,iLoc,b+tLoc-1]) * 0.333333);
		{|iLoc==0 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl-1,tBl,b+iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|iLoc==1 && Tl==0 && Nl==0 && b>=tLoc+1 && tLoc>=1 && b>=3} : (((temp_bl[iBl-1,tBl,b+iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
		{|Tl==0 && Nl==0 && iLoc>=2 && tLoc>=1 && b>=iLoc+1 && b>=tLoc+1 && b>=3} : (((temp_bl[iBl,tBl,iLoc-2,tLoc-1] + temp_bl[iBl,tBl,iLoc-1,tLoc-1]) + temp_bl[iBl,tBl,iLoc,tLoc-1]) * 0.333333);
	esac;
esac;


B_bl[iBl,iLoc] = case
	{|} : case
		{|Tl==0 && Nl==0 && iLoc>=0 && b>=3 && b>=iLoc+1} : temp_bl[Tb+iBl,Tb,Tl+iLoc,Tl];
	esac;
esac;
.
