/*
 * generated by Xtext
 */
package edu.csu.melange.alphabets.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AlphabetsRuntimeModule extends edu.csu.melange.alphabets.xtext.AbstractAlphabetsRuntimeModule {

}
