/*
* generated by Xtext
*/
package edu.csu.melange.alphabets.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AlphabetsOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
