/*
* generated by Xtext
*/
package edu.csu.melange.alphabets.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AlphabetsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("edu/csu/melange/alphabets/xtext/parser/antlr/internal/InternalAlphabets.tokens");
	}
}
