package tom.mapping.introspectors.scop;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EClass;

import tom.library.sl.Introspector;
import tom.mapping.IntrospectorManager;

import org.polymodel.scop.ScopPackage;

import org.polymodel.scop.*; 
import org.polymodel.scop.util.*;
import org.polymodel.scop.annotation.*; 
import org.polymodel.scop.annotation.util.*;
import org.polymodel.algebra.*; 
import org.polymodel.algebra.util.*;
import org.polymodel.algebra.affine.*; 
import org.polymodel.algebra.affine.util.*;
import org.polymodel.algebra.quasiAffine.*; 
import org.polymodel.algebra.quasiAffine.util.*;
import org.polymodel.algebra.polynomials.*; 
import org.polymodel.algebra.polynomials.util.*;
import org.polymodel.algebra.reductions.*; 
import org.polymodel.algebra.reductions.util.*;

/* PROTECTED REGION ID(introspector_imports) ENABLED START */
// protected imports
/* PROTECTED REGION END */

/**
* TOM introspector for scop.
* -- Autogenerated by TOM mapping EMF genrator --
*/

public class ScopIntrospector implements Introspector {
	
	public static final ScopIntrospector INSTANCE = new ScopIntrospector();
	
	static {
		IntrospectorManager.INSTANCE.register(ScopPackage.eINSTANCE, INSTANCE);
	}

	/* PROTECTED REGION ID(introspector_members) ENABLED START */
	/* PROTECTED REGION END */
	
	protected ScopIntrospector() {}
	
	public Object getChildAt(Object o, int i) {
		return getChildren(o)[i];
	}
	
	public int getChildCount(Object o) {
		return getChildren(o).length;
	}
	
	@SuppressWarnings("unchecked")
	public Object[] getChildren(Object arg0) {
		List<Object> l = new ArrayList<Object>();
		if (arg0 instanceof List) {
			// Children of a list are its content
			for(Object object : (List<Object>) arg0) {
				l.add(object);
			}
			return l.toArray();
		}
		return ScopChildrenGetter.INSTANCE.children(arg0);
	}
	
	private static class ScopChildrenGetter extends ScopSwitch<Object[]> {
		public final static ScopChildrenGetter INSTANCE = new ScopChildrenGetter();
		
		private ScopChildrenGetter(){}
		
		public Object[] children(Object i) {
			Object[] children = doSwitch((EObject) i);
			return children != null ? children : new Object[0];
		}
		
		public Object[] caseScopRoot(ScopRoot o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getStatements() != null)
				l.add(o.getStatements());
			
			/*PROTECTED REGION ID(getter_scop_ScopRoot) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopFor(ScopFor o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getIterator() != null)
				l.add(o.getIterator());
			if (o.getLB() != null)
				l.add(o.getLB());
			if (o.getUB() != null)
				l.add(o.getUB());
			if (o.getStride() != null)
				l.add(o.getStride());
			if (o.getBody() != null)
				l.add(o.getBody());
			
			/*PROTECTED REGION ID(getter_scop_ScopFor) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopBlock(ScopBlock o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getStatements() != null)
				l.add(o.getStatements());
			
			/*PROTECTED REGION ID(getter_scop_ScopBlock) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopGuard(ScopGuard o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getConstraintSystems() != null)
				l.add(o.getConstraintSystems());
			if (o.getThenBody() != null)
				l.add(o.getThenBody());
			if (o.getElseBody() != null)
				l.add(o.getElseBody());
			
			/*PROTECTED REGION ID(getter_scop_ScopGuard) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopStatementMacro(ScopStatementMacro o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getMacroParams() != null)
				l.add(o.getMacroParams());
			
			/*PROTECTED REGION ID(getter_scop_ScopStatementMacro) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopAssignment(ScopAssignment o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getLHS() != null)
				l.add(o.getLHS());
			if (o.getRHS() != null)
				l.add(o.getRHS());
			
			/*PROTECTED REGION ID(getter_scop_ScopAssignment) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
		
		public Object[] caseScopUnscannedDomain(ScopUnscannedDomain o) {
			List<Object> l = new ArrayList<Object>();
			if (o.getMacroParams() != null)
				l.add(o.getMacroParams());
			
			/*PROTECTED REGION ID(getter_scop_ScopUnscannedDomain) ENABLED START*/
			/*PROTECTED REGION END*/
			
			return l.toArray();
		}
	}
	
	@SuppressWarnings("unchecked")
	public <T> T setChildren(T arg0, Object[] arg1) {
		if (arg0 instanceof List) {
			// If object is a list then content of the original list has to be replaced
			List<Object> list = (List<Object>) arg0;
			list.clear();
			for (int i = 0; i < arg1.length; i++) {
				list.add(arg1[i]);
			}
			return arg0;
		} else {
			return (T) ScopChildrenSetter.INSTANCE.set(arg0, arg1);
		}
	}
	
	private static class ScopChildrenSetter extends ScopSwitch<Object> {
		public final static ScopChildrenSetter INSTANCE = new ScopChildrenSetter();
		
		private Object[] children;
		private ScopChildrenSetter(){}
		
		public Object set(Object i, Object[] children) {
			this.children = children;
			return doSwitch((EObject) i);
		}
		
		public Object caseScopFor(ScopFor o) {
			o.setIterator((Variable)children[0]);
			o.setLB((IntExpression)children[1]);
			o.setUB((IntExpression)children[2]);
			o.setStride((IntExpression)children[3]);
			o.setBody((AbstractScopNode)children[4]);
		
			/*PROTECTED REGION ID(setter_scop_ScopFor) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
		
		public Object caseScopGuard(ScopGuard o) {
			o.setThenBody((AbstractScopNode)children[0]);
			o.setElseBody((AbstractScopNode)children[1]);
		
			/*PROTECTED REGION ID(setter_scop_ScopGuard) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
		
		public Object caseScopAssignment(ScopAssignment o) {
			o.setLHS((Variable)children[0]);
			o.setRHS((IntExpression)children[1]);
		
			/*PROTECTED REGION ID(setter_scop_ScopAssignment) ENABLED START*/
			/*PROTECTED REGION END*/
		
			return o;
		}
	}

	public <T> T setChildAt(T o, int i, Object obj) {
		throw new RuntimeException("Not implemented");
	}
}
