affine deriche {W,H| W>=0 && H>=0 }
	input
		double a {j0| -j0+3>=0 && j0-1>=0 && W-1>=0 && H-1>=0 } || {j0| -j0+8>=0 && j0-5>=0 && W-1>=0 && H-1>=0 } ;
		double b {j0| -j0+2>=0 && j0-1>=0 && W-1>=0 && H-1>=0 } ;
		double in {j0,j1| j0>=0 && -j0+W-1>=0 && -j1+H-1>=0 && j1>=0 } ;
	output
		double S33 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
	local
		double S3 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
		double S5 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
		double S11 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
		double S12 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
		double S14 {i,j| i>=0 && -i+W-1>=0 && -j+H-1>=0 && j>=0 } ;
		double S20 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S21 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S22 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S28 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S29 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S30 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
		double S31 {j,i| j>=0 && -j+H-1>=0 && -i+W-1>=0 && i>=0 } ;
	let
		S3[i,j] = case
			{ | j==0 } : (a[1] * in) ;
			{ | j-1>=0 } : ((((a[1] * in) + (a[2] * in[i,j-1])) + (b[1] * S3[i,j-1])) + (b[2] * S5[i,j-1])) ;
		esac;
		S5[i,j] = case
			{ | j==0 } : 0 ;
			{ | j-1>=0 } : S3[i,j-1] ;
		esac;
		S11[i,j] = case
			{ | j-H+1==0 } : 0 ;
			{ | -j+H-2>=0 } : ((((a[3] * in[i,j+1]) + (a[1] * S12[i,j+1])) + (b[1] * S11[i,j+1])) + (b[2] * S14[i,j+1])) ;
		esac;
		S12[i,j] = case
			{ | j-H+1==0 } : 0 ;
			{ | -j+H-2>=0 } : in[i,j+1] ;
		esac;
		S14[i,j] = case
			{ | j-H+1==0 } : 0 ;
			{ | -j+H-2>=0 } : S11[i,j+1] ;
		esac;
		S20[j,i] = case
			{ | i==0 } : (a[5] * (S3[i,j] + S11[i,j])) ;
			{ | i-1>=0 } : ((((a[5] * (S3[i,j] + S11[i,j])) + (a[6] * S21[j,i-1])) + (b[1] * S20[j,i-1])) + (b[2] * S22[j,i-1]))
			;
		esac;
		S21[j,i] = (S3[i,j] + S11[i,j]);
		S22[j,i] = case
			{ | i==0 } : 0 ;
			{ | i-1>=0 } : S20[j,i-1] ;
		esac;
		S28[j,i] = case
			{ | i-W+1==0 } : 0 ;
			{ | -i+W-2>=0 } : ((((a[7] * S30[j,i+1]) + (a[8] * S29[j,i+1])) + (b[1] * S30[j,i+1])) + (b[2] * S29[j,i+1])) ;
		esac;
		S29[j,i] = case
			{ | i-W+1==0 } : 0 ;
			{ | -i+W-2>=0 } : S30[j,i+1] ;
		esac;
		S30[j,i] = (S3[i,j] + S11[i,j]);
		S31[j,i] = case
			{ | i-W+1==0 } : 0 ;
			{ | -i+W-2>=0 } : S28[j,i+1] ;
		esac;
		S33[i,j] = (S20[j,i] + S28[j,i]);
.

