/*
 * generated by Xtext
 */
package edu.csu.melange.alphabets.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.csu.melange.alphabets.xtext.ui.internal.AlphabetsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlphabetsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AlphabetsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AlphabetsActivator.getInstance().getInjector(AlphabetsActivator.EDU_CSU_MELANGE_ALPHABETS_XTEXT_ALPHABETS);
	}
	
}
