package fr.irisa.cairn.jnimap.cloog.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ClastGuard_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIClastGuard extends JNIClastStmt {
	
	
	/* @generated */
	protected JNIClastGuard(long ptr) {
		/*** PROTECTED REGION ID(ClastGuard_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	
		public Object accept(IClastStmtVisitor visitor, Object arg) {
			return visitor.visitJNIClastGuard(this, arg);
		}
	
	
	/*** PROTECTED REGION ID(ClastGuard_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/

	/*************************************** 
	 *	     Struct Field Accessors        * 
	 ***************************************/
	/*************************************************************
	 *	then : JNIClastStmt
	 *************************************************************/
	public JNIClastStmt getThen() {
		return JNIClastStmt.build(CloogNative.clast_guard_get_then(getNativePtr(this)));
	}
	/*************************************************************
	 *	then : JNIClastStmt
	 *************************************************************/
	public void setThen(JNIClastStmt object) {
		CloogNative.clast_guard_set_then(getNativePtr(this), getNativePtr(object));
	}
	/*************************************************************
	 * Test if Tthen is NULL
	 *************************************************************/
	public boolean testThen() {
		return CloogNative.clast_guard_test_then(getNativePtr(this)) != 0;
	}
	/*************************************************************
	 *	n : int
	 *************************************************************/
	public int getN() {
		return CloogNative.clast_guard_get_n(getNativePtr(this));
	}
	/*************************************************************
	 *	n : int
	 *************************************************************/
	public void setN(int object) {
		CloogNative.clast_guard_set_n(getNativePtr(this), object);
	}
	/*************************************************************
	 * Test if Tn is NULL
	 *************************************************************/
	public boolean testN() {
		return CloogNative.clast_guard_test_n(getNativePtr(this)) != 0;
	}

	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * clast_guard_get_equation 
	 * 
	 * @generated
	**/
	public JNIClastEquation getEquation(int offset) {
		/*** PROTECTED REGION ID(clast_guard_get_equation) DISABLED START ***/
		JNIClastEquation res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIClastEquation.build(CloogNative.clast_guard_get_equation(getNativePtr(this), offset));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ClastGuard_toString) DISABLED START ***/
			return CloogPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
