package fr.irisa.cairn.jnimap.cloog.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ClastAssignment_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIClastAssignment extends JNIClastStmt {
	
	
	/* @generated */
	protected JNIClastAssignment(long ptr) {
		/*** PROTECTED REGION ID(ClastAssignment_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	
		public Object accept(IClastStmtVisitor visitor, Object arg) {
			return visitor.visitJNIClastAssignment(this, arg);
		}
	
	
	/*** PROTECTED REGION ID(ClastAssignment_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/

	/*************************************** 
	 *	     Struct Field Accessors        * 
	 ***************************************/
	/*************************************************************
	 *	LHS : String
	 *************************************************************/
	public String getLHS() {
		return CloogNative.clast_assignment_get_LHS(getNativePtr(this));
	}
	/*************************************************************
	 *	LHS : String
	 *************************************************************/
	public void setLHS(String object) {
		CloogNative.clast_assignment_set_LHS(getNativePtr(this), object);
	}
	/*************************************************************
	 * Test if TLHS is NULL
	 *************************************************************/
	public boolean testLHS() {
		return CloogNative.clast_assignment_test_LHS(getNativePtr(this)) != 0;
	}
	/*************************************************************
	 *	RHS : JNIClastExpr
	 *************************************************************/
	public JNIClastExpr getRHS() {
		return JNIClastExpr.build(CloogNative.clast_assignment_get_RHS(getNativePtr(this)));
	}
	/*************************************************************
	 *	RHS : JNIClastExpr
	 *************************************************************/
	public void setRHS(JNIClastExpr object) {
		CloogNative.clast_assignment_set_RHS(getNativePtr(this), getNativePtr(object));
	}
	/*************************************************************
	 * Test if TRHS is NULL
	 *************************************************************/
	public boolean testRHS() {
		return CloogNative.clast_assignment_test_RHS(getNativePtr(this)) != 0;
	}

	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	
	public String toString() {
		/*** PROTECTED REGION ID(ClastAssignment_toString) DISABLED START ***/
			return CloogPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
