package fr.irisa.cairn.jnimap.cloog.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ClastBlock_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIClastBlock extends JNIClastStmt {
	
	
	/* @generated */
	protected JNIClastBlock(long ptr) {
		/*** PROTECTED REGION ID(ClastBlock_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	
		public Object accept(IClastStmtVisitor visitor, Object arg) {
			return visitor.visitJNIClastBlock(this, arg);
		}
	
	
	/*** PROTECTED REGION ID(ClastBlock_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/

	/*************************************** 
	 *	     Struct Field Accessors        * 
	 ***************************************/
	/*************************************************************
	 *	body : JNIClastStmt
	 *************************************************************/
	public JNIClastStmt getBody() {
		return JNIClastStmt.build(CloogNative.clast_block_get_body(getNativePtr(this)));
	}
	/*************************************************************
	 *	body : JNIClastStmt
	 *************************************************************/
	public void setBody(JNIClastStmt object) {
		CloogNative.clast_block_set_body(getNativePtr(this), getNativePtr(object));
	}
	/*************************************************************
	 * Test if Tbody is NULL
	 *************************************************************/
	public boolean testBody() {
		return CloogNative.clast_block_test_body(getNativePtr(this)) != 0;
	}

	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	
	public String toString() {
		/*** PROTECTED REGION ID(ClastBlock_toString) DISABLED START ***/
			return CloogPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
