/*
 * PCOT benchmark : Gauss-Seidel 2D
 * 
 * This is a 9-point stencil with 2D space and 1D time.
 */ 
 
 affine GS2D { T,N | T > 2 && N > 5 }
 
	input
		double Ain { i,j | 0 <= i,j < N } ;
	output
		double Aout { i,j | 0 <= i,j < N } ;
	local
		double temp { t,i,j | 0 <= i,j < N && 0 <= t < T } ;
		
	let
		temp[t,i,j] = 
					case
						{ | t == 0 } : Ain[i,j] ;
						
						{ | t > 0 && 1 <= (i,j) < N-1 } : 
								(temp[t,i-1,j-1] + temp[t,i-1,j] + temp[t,i-1,j+1] + temp[t,i,j-1] + temp[t-1,i,j] 
									+ temp[t-1,i,j+1] + temp[t-1,i+1,j-1] + temp[t-1,i+1,j] + temp[t-1,i+1,j+1]) / 9.0 ;
									
						{ | t > 0 && i == 0 } || { | t > 0 && j == 0 } || { | t > 0 && i == N-1 } || { | t > 0 && j == N-1 } : temp[t-1,i,j] ;
					esac;
		
		Aout[i,j] = temp[T-1,i,j] ;
.