package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLIdentifier_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLIdentifier extends JNIObject {
	
	/* @generated */
	protected JNIISLIdentifier(long ptr) {
		/*** PROTECTED REGION ID(ISLIdentifier_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	/* @generated */
	protected static JNIISLIdentifier build(long ptr) {
		return new JNIISLIdentifier(ptr);
	}
	
	/*** PROTECTED REGION ID(ISLIdentifier_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/


	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	/**
	 * isl_id_alloc 
	 * 
	 * @generated
	**/
	 public static JNIISLIdentifier alloc(JNIISLContext ctx, String name) { 
		/*** PROTECTED REGION ID(static_isl_id_alloc) DISABLED START ***/
		JNIISLIdentifier res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLIdentifier.build(ISLNative.isl_id_alloc(getNativePtr(ctx), name));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_id_to_string 
	 * 
	 * @generated
	**/
	 public static String _toString(JNIISLIdentifier id, int format) { 
		/*** PROTECTED REGION ID(static_isl_id_to_string) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_id_to_string(getNativePtr(id), format);
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * isl_id_get_ctx 
	 * 
	 * @generated
	**/
	public JNIISLContext getContext() {
		/*** PROTECTED REGION ID(isl_id_get_ctx) DISABLED START ***/
		JNIISLContext res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLContext.build(ISLNative.isl_id_get_ctx(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_id_get_name 
	 * 
	 * @generated
	**/
	public String getName() {
		/*** PROTECTED REGION ID(isl_id_get_name) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_id_get_name(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_id_get_user 
	 * 
	 * @generated
	**/
	public long islIdGetUser() {
		/*** PROTECTED REGION ID(isl_id_get_user) DISABLED START ***/
		long res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_id_get_user(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_id_copy 
	 * 
	 * @generated
	**/
	public JNIISLIdentifier copy() {
		/*** PROTECTED REGION ID(isl_id_copy) DISABLED START ***/
		JNIISLIdentifier res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLIdentifier.build(ISLNative.isl_id_copy(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_id_free 
	 * 
	 * @take this
	 * @generated
	**/
	public void free() {
		/*** PROTECTED REGION ID(isl_id_free) DISABLED START ***/
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				ISLNative.isl_id_free(getNativePtr(this));
			} finally {
				taken(this);
			}
		}
		
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLIdentifier_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
