package fr.irisa.cairn.jnimap.isl.jni;

import java.util.HashMap;
import java.util.Map;

/*** PROTECTED REGION ID(ISLAstOpType_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */

public class JNIISLAstOpType  {

	int value;
	String name;

	/*** PROTECTED REGION ID(ISLAstOpType_values) DISABLED START ***/
	public static final int ISL_AST_OP_AND = 0;
	public static final int ISL_AST_OP_AND_THEN = 1;
	public static final int ISL_AST_OP_OR = 2;
	public static final int ISL_AST_OP_OR_ELSE = 3;
	public static final int ISL_AST_OP_MAX = 4;
	public static final int ISL_AST_OP_MIN = 5;
	public static final int ISL_AST_OP_MINUS = 6;
	public static final int ISL_AST_OP_ADD = 7;
	public static final int ISL_AST_OP_SUB = 8;
	public static final int ISL_AST_OP_MUL = 9;
	public static final int ISL_AST_OP_DIV = 10;
	public static final int ISL_AST_OP_FDIV_Q = 11;
	public static final int ISL_AST_OP_PDIV_Q = 12;
	public static final int ISL_AST_OP_PDIV_R = 13;
	public static final int ISL_AST_OP_ZDIV_R = 14;
	public static final int ISL_AST_OP_COND = 15;
	public static final int ISL_AST_OP_SELECT = 16;
	public static final int ISL_AST_OP_EQ = 17;
	public static final int ISL_AST_OP_LE = 18;
	public static final int ISL_AST_OP_LT = 19;
	public static final int ISL_AST_OP_GE = 20;
	public static final int ISL_AST_OP_GT = 21;
	public static final int ISL_AST_OP_CALL = 22;
	public static final int ISL_AST_OP_ACCESS = 23;
	public static final int ISL_AST_OP_MEMBER = 24;
	public static final int ISL_AST_OP_ADDRESS_OF = 25;
	/*** PROTECTED REGION END ***/
	
	public static JNIISLAstOpType isl_ast_op_and = new JNIISLAstOpType("isl_ast_op_and", ISL_AST_OP_AND);
	public static JNIISLAstOpType isl_ast_op_and_then = new JNIISLAstOpType("isl_ast_op_and_then", ISL_AST_OP_AND_THEN);
	public static JNIISLAstOpType isl_ast_op_or = new JNIISLAstOpType("isl_ast_op_or", ISL_AST_OP_OR);
	public static JNIISLAstOpType isl_ast_op_or_else = new JNIISLAstOpType("isl_ast_op_or_else", ISL_AST_OP_OR_ELSE);
	public static JNIISLAstOpType isl_ast_op_max = new JNIISLAstOpType("isl_ast_op_max", ISL_AST_OP_MAX);
	public static JNIISLAstOpType isl_ast_op_min = new JNIISLAstOpType("isl_ast_op_min", ISL_AST_OP_MIN);
	public static JNIISLAstOpType isl_ast_op_minus = new JNIISLAstOpType("isl_ast_op_minus", ISL_AST_OP_MINUS);
	public static JNIISLAstOpType isl_ast_op_add = new JNIISLAstOpType("isl_ast_op_add", ISL_AST_OP_ADD);
	public static JNIISLAstOpType isl_ast_op_sub = new JNIISLAstOpType("isl_ast_op_sub", ISL_AST_OP_SUB);
	public static JNIISLAstOpType isl_ast_op_mul = new JNIISLAstOpType("isl_ast_op_mul", ISL_AST_OP_MUL);
	public static JNIISLAstOpType isl_ast_op_div = new JNIISLAstOpType("isl_ast_op_div", ISL_AST_OP_DIV);
	public static JNIISLAstOpType isl_ast_op_fdiv_q = new JNIISLAstOpType("isl_ast_op_fdiv_q", ISL_AST_OP_FDIV_Q);
	public static JNIISLAstOpType isl_ast_op_pdiv_q = new JNIISLAstOpType("isl_ast_op_pdiv_q", ISL_AST_OP_PDIV_Q);
	public static JNIISLAstOpType isl_ast_op_pdiv_r = new JNIISLAstOpType("isl_ast_op_pdiv_r", ISL_AST_OP_PDIV_R);
	public static JNIISLAstOpType isl_ast_op_zdiv_r = new JNIISLAstOpType("isl_ast_op_zdiv_r", ISL_AST_OP_ZDIV_R);
	public static JNIISLAstOpType isl_ast_op_cond = new JNIISLAstOpType("isl_ast_op_cond", ISL_AST_OP_COND);
	public static JNIISLAstOpType isl_ast_op_select = new JNIISLAstOpType("isl_ast_op_select", ISL_AST_OP_SELECT);
	public static JNIISLAstOpType isl_ast_op_eq = new JNIISLAstOpType("isl_ast_op_eq", ISL_AST_OP_EQ);
	public static JNIISLAstOpType isl_ast_op_le = new JNIISLAstOpType("isl_ast_op_le", ISL_AST_OP_LE);
	public static JNIISLAstOpType isl_ast_op_lt = new JNIISLAstOpType("isl_ast_op_lt", ISL_AST_OP_LT);
	public static JNIISLAstOpType isl_ast_op_ge = new JNIISLAstOpType("isl_ast_op_ge", ISL_AST_OP_GE);
	public static JNIISLAstOpType isl_ast_op_gt = new JNIISLAstOpType("isl_ast_op_gt", ISL_AST_OP_GT);
	public static JNIISLAstOpType isl_ast_op_call = new JNIISLAstOpType("isl_ast_op_call", ISL_AST_OP_CALL);
	public static JNIISLAstOpType isl_ast_op_access = new JNIISLAstOpType("isl_ast_op_access", ISL_AST_OP_ACCESS);
	public static JNIISLAstOpType isl_ast_op_member = new JNIISLAstOpType("isl_ast_op_member", ISL_AST_OP_MEMBER);
	public static JNIISLAstOpType isl_ast_op_address_of = new JNIISLAstOpType("isl_ast_op_address_of", ISL_AST_OP_ADDRESS_OF);
	
	public static JNIISLAstOpType build(long value) {
		return getFromInt((int) value) ;
	}
	
	
	public static  JNIISLAstOpType getFromInt(int value) {
		/*** PROTECTED REGION ID(ISLAstOpType_getValues) ENABLED START ***/
		switch (value) {
			case ISL_AST_OP_AND :
				return isl_ast_op_and;
			case ISL_AST_OP_AND_THEN :
				return isl_ast_op_and_then;
			case ISL_AST_OP_OR :
				return isl_ast_op_or;
			case ISL_AST_OP_OR_ELSE :
				return isl_ast_op_or_else;
			case ISL_AST_OP_MAX :
				return isl_ast_op_max;
			case ISL_AST_OP_MIN :
				return isl_ast_op_min;
			case ISL_AST_OP_MINUS :
				return isl_ast_op_minus;
			case ISL_AST_OP_ADD :
				return isl_ast_op_add;
			case ISL_AST_OP_SUB :
				return isl_ast_op_sub;
			case ISL_AST_OP_MUL :
				return isl_ast_op_mul;
			case ISL_AST_OP_DIV :
				return isl_ast_op_div;
			case ISL_AST_OP_FDIV_Q :
				return isl_ast_op_fdiv_q;
			case ISL_AST_OP_ZDIV_R :
				return isl_ast_op_zdiv_r;
			case ISL_AST_OP_PDIV_Q :
				return isl_ast_op_pdiv_q;
			case ISL_AST_OP_PDIV_R :
				return isl_ast_op_pdiv_r;
			case ISL_AST_OP_COND :
				return isl_ast_op_cond;
			case ISL_AST_OP_SELECT :
				return isl_ast_op_select;
			case ISL_AST_OP_EQ :
				return isl_ast_op_eq;
			case ISL_AST_OP_LE :
				return isl_ast_op_le;
			case ISL_AST_OP_LT :
				return isl_ast_op_lt;
			case ISL_AST_OP_GE :
				return isl_ast_op_ge;
			case ISL_AST_OP_GT :
				return isl_ast_op_gt;
			case ISL_AST_OP_CALL :
				return isl_ast_op_call;

			default :
				return null;
		}
		/*** PROTECTED REGION END ***/
	}

	private JNIISLAstOpType(String name, int value) {
		this.value=value;
		this.name=name;
	}
	
	public int getValue() {
		return this.value;
	}

	public String getName() {
		return this.name;
	}
	
}
