package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLLocalSpace_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLLocalSpace extends JNIObject {
	
	/* @generated */
	protected JNIISLLocalSpace(long ptr) {
		/*** PROTECTED REGION ID(ISLLocalSpace_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	/* @generated */
	protected static JNIISLLocalSpace build(long ptr) {
		return new JNIISLLocalSpace(ptr);
	}
	
	/*** PROTECTED REGION ID(ISLLocalSpace_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/


	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	/**
	 * isl_local_space_from_space 
	 * 
	@take dim
	 * @generated
	**/
	 public static JNIISLLocalSpace fromSpace(JNIISLSpace dim) { 
		/*** PROTECTED REGION ID(static_isl_local_space_from_space) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(dim);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_from_space(getNativePtr(dim)));
			} finally {
				taken(dim);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * isl_local_space_get_ctx 
	 * 
	 * @generated
	**/
	public JNIISLContext getContext() {
		/*** PROTECTED REGION ID(isl_local_space_get_ctx) DISABLED START ***/
		JNIISLContext res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLContext.build(ISLNative.isl_local_space_get_ctx(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_get_space 
	 * 
	 * @generated
	**/
	public JNIISLSpace getSpace() {
		/*** PROTECTED REGION ID(isl_local_space_get_space) DISABLED START ***/
		JNIISLSpace res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLSpace.build(ISLNative.isl_local_space_get_space(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_copy 
	 * 
	 * @generated
	**/
	public JNIISLLocalSpace copy() {
		/*** PROTECTED REGION ID(isl_local_space_copy) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_copy(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_free 
	 * 
	 * @take this
	 * @generated
	**/
	public void free() {
		/*** PROTECTED REGION ID(isl_local_space_free) DISABLED START ***/
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				ISLNative.isl_local_space_free(getNativePtr(this));
			} finally {
				taken(this);
			}
		}
		
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_is_set 
	 * 
	 * @generated
	**/
	public boolean isSetSpace() {
		/*** PROTECTED REGION ID(isl_local_space_is_set) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_local_space_is_set(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_dim 
	 * 
	 * @generated
	**/
	public int getNbDims(JNIISLDimType type) {
		/*** PROTECTED REGION ID(isl_local_space_dim) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_local_space_dim(getNativePtr(this), type.getValue());
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_has_dim_name 
	 * 
	 * @generated
	**/
	public boolean hasName(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_local_space_has_dim_name) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_local_space_has_dim_name(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_get_dim_name 
	 * 
	 * @generated
	**/
	public String getName(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_local_space_get_dim_name) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_local_space_get_dim_name(getNativePtr(this), type.getValue(), pos);
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_set_dim_name 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace setName(JNIISLDimType type, int pos, String s) {
		/*** PROTECTED REGION ID(isl_local_space_set_dim_name) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_set_dim_name(getNativePtr(this), type.getValue(), pos, s));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_get_div 
	 * 
	 * @generated
	**/
	public JNIISLAff getDivAt(int pos) {
		/*** PROTECTED REGION ID(isl_local_space_get_div) DISABLED START ***/
		JNIISLAff res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLAff.build(ISLNative.isl_local_space_get_div(getNativePtr(this), pos));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_is_equal 
	 * 
	 * @generated
	**/
	public boolean isEqual(JNIISLLocalSpace ls2) {
		/*** PROTECTED REGION ID(isl_local_space_is_equal) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_local_space_is_equal(getNativePtr(this), getNativePtr(ls2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_domain 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace domain() {
		/*** PROTECTED REGION ID(isl_local_space_domain) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_domain(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_range 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace range() {
		/*** PROTECTED REGION ID(isl_local_space_range) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_range(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_from_domain 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace fromDomain() {
		/*** PROTECTED REGION ID(isl_local_space_from_domain) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_from_domain(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_flatten_domain 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace flattenDomain() {
		/*** PROTECTED REGION ID(isl_local_space_flatten_domain) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_flatten_domain(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_flatten_range 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace flattenRange() {
		/*** PROTECTED REGION ID(isl_local_space_flatten_range) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_flatten_range(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_lifting 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicMap lifting() {
		/*** PROTECTED REGION ID(isl_local_space_lifting) DISABLED START ***/
		JNIISLBasicMap res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicMap.build(ISLNative.isl_local_space_lifting(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_add_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace addDims(JNIISLDimType type, int n) {
		/*** PROTECTED REGION ID(isl_local_space_add_dims) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_add_dims(getNativePtr(this), type.getValue(), n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_insert_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace insertDims(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_local_space_insert_dims) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_insert_dims(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_drop_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLLocalSpace dropDims(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_local_space_drop_dims) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_drop_dims(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_local_space_intersect 
	 * 
	 * @take this ls2
	 * @generated
	**/
	public JNIISLLocalSpace intersect(JNIISLLocalSpace ls2) {
		/*** PROTECTED REGION ID(isl_local_space_intersect) DISABLED START ***/
		JNIISLLocalSpace res;
		
		synchronized(LOCK) {
			checkParameters(this, ls2);
			try {
				res = JNIISLLocalSpace.build(ISLNative.isl_local_space_intersect(getNativePtr(this), getNativePtr(ls2)));
			} finally {
				taken(this);
				taken(ls2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLLocalSpace_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
