package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLSet_userImport) ENABLED START ***/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLSet extends JNIObject {
	
	/* @generated */
	protected JNIISLSet(long ptr) {
		/*** PROTECTED REGION ID(ISLSet_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	/* @generated */
	protected static JNIISLSet build(long ptr) {
		return new JNIISLSet(ptr);
	}
	
	/*** PROTECTED REGION ID(ISLSet_userCode) ENABLED START ***/

	public JNIISLMap toIdentityMap() {
		return buildIdentityMap();
	}

	public JNIISLMap buildIdentityMap() {
		JNIISLMap map = JNIISLMap.fromDomainAndRange(this.copy(), this.copy());
		for (int i = 0; i < this.getNbDims(); i++) {
			map = map.sliceEquate(JNIISLDimType.isl_dim_in, i, JNIISLDimType.isl_dim_out, i);
		}
		return map;
	}

	 //deprecated methods for (partial) backwards compatibility
	@Deprecated
	public JNIISLSet(JNIISLContext ctx, String str) {
		this(ISLNative.isl_set_read_from_str(getNativePtr(ctx), str));
	}
	
	@Deprecated
	public int getNumberOfBasicSet() {
		return this.getNbBasicSets();
	}

	@Deprecated
	public boolean equivalent(JNIISLSet set) {
		return (this.isEqual(set));
	}

	@Deprecated
	public boolean empty() {
		return (this.isEmpty());
	}
	
	@Deprecated
	public JNIISLSet paramsSet() {
		return paramSet();
	}
	
	@Deprecated
	public int getNParam() {
		return getNbParams();
	}

	@Deprecated
	public static JNIISLSet subtract(JNIISLSet set1, JNIISLSet set2) {
		return set1.subtract(set2);
	}

	@Deprecated
	public static JNIISLSet intersect(JNIISLSet set1, JNIISLSet set2) {
		return set1.intersect(set2);
	}
	
	@Deprecated
	public static JNIISLSet union(JNIISLSet set1, JNIISLSet set2) {
		return set1.union(set2);
	}
	
	
	@Deprecated
	public static JNIISLSet buildUniverseLike(JNIISLSet set) {
		return JNIISLSet.buildUniverse(set.getSpace());
	}
	
	@Deprecated
	public int getNDim() {
		return getNbDims();
	}
	
	@Deprecated
	public static JNIISLSet fromBasicSet(JNIISLBasicSet bset) {
		return bset.toSet();
	}
	
	@Deprecated
	public JNIISLSet insertDim(JNIISLDimType type, int pos, int n) {
		return insertDims(type, pos, n);
	}
	
	@Deprecated
	public JNIISLMap lexNextMap(int nbInnerLoop) {
		return getLexNextMap(nbInnerLoop);
	}

	@Deprecated
	public JNIISLMap lexPredMap(int nbInnerLoop) {
		return getLexPredMap(nbInnerLoop);
	}

	
	@Deprecated
	public JNIISLMap lexNextPowerMap(int nbInnerLoop, int power) {
		return getLexNextPowerMap(nbInnerLoop, power);
	}

	@Deprecated
	public JNIISLMap lexPredPowerMap(int nbInnerLoop, int power) {
		return getLexPredPowerMap(nbInnerLoop, power);
	}
	
	public static JNIISLSet buildFromString(String str) {
		return buildFromString(JNIISLContext.getCtx(), str);
	}
	
	public JNIISLSet eliminateDims(int first, int n) {
		return eliminate(JNIISLDimType.isl_dim_set, first, n);
	}

	public JNIISLSet extend(int nparam, int dim) {
		JNIISLSet res = this.addDims(JNIISLDimType.isl_dim_param, nparam);
		res = res.addDims(JNIISLDimType.isl_dim_set, dim);
		return res;
	}
	
	public JNIISLMap testttt() {
		long lex_next = ISLNative.UserModules.lex_next(getNativePtr(this), 2);
		System.out.println("computed");
		return JNIISLMap.build(lex_next);
	}
	
	public JNIISLSet projectOutAllBut(JNIISLDimType dimType, int i) {
		JNIISLSet res = this.copy();
		int nb = this.getNbDims(dimType);
		if (i>0) res = res.projectOut(dimType,0,i);
		if (i<nb-1) res = res.projectOut(dimType,1,nb-1-i);
		return res;
	}
	
	public static JNIISLSet buildEmptyLike(JNIISLSet set) {
		return buildEmpty(set.getSpace());
	}
	
	/**
	 * computes this.detectEqualities().coalesce().removeRedundancies() and
	 * then tries, in order to reduce the number of basic sets : 
	 * this.copy().simpleHull().toSet().subtract(this.copy().complement());
	 */
	public JNIISLSet simplify() {
		JNIISLSet s = this.detectEqualities().coalesce().removeRedundancies();
		JNIISLSet simplify = s.copy().simpleHull().toSet()
				.subtract(s.copy().complement());
		if (simplify.getNbBasicSets() < s.getNbBasicSets())
			s = simplify;
		s = s.detectEqualities().coalesce().removeRedundancies();
		return s;
	}

	
	public JNIISLSet pad(int dim, int size) {
		JNIISLSet res = this.copy();

		JNIISLBasicMap shift = JNIISLBasicMap.buildUniverse(JNIISLSpace
				.idMapDimFromSetDim(res.getSpace().copy()));
		long n = res.getSpace().getNbDims(JNIISLDimType.isl_dim_set);
		for (int i = 0; i < n; i++) {
			if (i != dim) {
				JNIISLConstraint c = JNIISLConstraint.buildEquality(JNIISLLocalSpace
						.fromSpace(shift.getSpace().copy()));
				c = c.setCoefficient(JNIISLDimType.isl_dim_in, i, 1);
				c = c.setCoefficient(JNIISLDimType.isl_dim_out, i, -1);
				shift = shift.addConstraint(c);
			} else {
				JNIISLConstraint c1 = JNIISLConstraint
						.buildInequality(JNIISLLocalSpace.fromSpace(shift.getSpace()
								.copy()));
				c1 = c1.setCoefficient(JNIISLDimType.isl_dim_in, i, -1);
				c1 = c1.setCoefficient(JNIISLDimType.isl_dim_out, i, 1);

				JNIISLConstraint c2 = JNIISLConstraint
						.buildInequality(JNIISLLocalSpace.fromSpace(shift.getSpace()
								.copy()));
				c2 = c2.setCoefficient(JNIISLDimType.isl_dim_in, i, 1);
				c2 = c2.setCoefficient(JNIISLDimType.isl_dim_out, i, -1);
				c2 = c2.setConstant(size);

				shift = shift.addConstraint(c1);
				shift = shift.addConstraint(c2);
			}
		}
		JNIISLMap shiftMap = shift.toMap();
		res = res.apply(shiftMap);
		return res.coalesce();
	}

	public JNIISLSet expandTo(JNIISLSet mergedDomains) {
		return JNIISLTools.expandTo(this, mergedDomains);
	}

	public List<JNIISLBasicSet> getBasicSets() {
		List<JNIISLBasicSet> res = new ArrayList<JNIISLBasicSet>();
		for (int i = 0; i < getNbBasicSets(); i++) {
			res.add(getBasicSetAt(i));
		}
		return res;
	}

	public String toString(ISL_FORMAT format) {
		return ISLPrettyPrinter.asString(this, format);
	}

	public static String asList(List<? extends Object> objs, String sep) {
		String res = "";
		boolean first = true;
		for (Object obj : objs) {
			if (!first) {
				res += sep;
			}
			res += obj.toString();
			first = false;
		}
		return res;

	}

	public JNIISLSet convertTo(JNIISLSpace target) {
		JNIISLSpace space = this.getSpace();
		if (target.getNbDims(JNIISLDimType.isl_dim_param) != space
				.getNbDims(JNIISLDimType.isl_dim_param)) {
			throw new UnsupportedOperationException(
					"Parameter mismatch : cannnot convert " + space + " to "
							+ target);
		} else {
			String mapStr = "" + this.getParametersNames() + "-> { "
					+ getIndicesNames() + " ->  "
					+ target.getNameList(JNIISLDimType.isl_dim_set) + "  :";
			List<String> nameList = space
					.getNameList(JNIISLDimType.isl_dim_set);
			List<String> assgnList = new ArrayList<String>();
			List<String> targetNames = target
					.getNameList(JNIISLDimType.isl_dim_set);
			int insize = nameList.size();
			for (int i = 0; i < insize; i++) {
				assgnList.add(targetNames.get(i) + "=" + nameList.get(i));
			}
			mapStr += asList(assgnList, " & ") + " }";
			JNIISLMap islMap = ISLFactory.islMap(mapStr);
			return this.copy().apply(islMap);
		}
	}

	public List<String> getParametersNames() {
		JNIISLSpace space = getSpace();
		int nbParams = (int) space.getNbDims(JNIISLDimType.isl_dim_param);//for(StringBuffer dim : map.get)
		List<String> params = new ArrayList<String>();
		for (int i = 0; i < nbParams; i++) {
			String name = space.getName(JNIISLDimType.isl_dim_param, i);
			params.add(name);
		}
		return params;
	}

	public List<String> getIndicesNames() {
		int nbIndices = (int) getSpace().getNbDims(JNIISLDimType.isl_dim_set);//for(StringBuffer dim : map.get)
		List<String> indices = new ArrayList<String>();
		for (int i = 0; i < nbIndices; i++) {
			String name = getSpace().getName(JNIISLDimType.isl_dim_set, i);
			if (name == null) {
				name = "i" + i;
			}
			indices.add(name);
		}
		return indices;
	}

	public List<JNIISLPoint> getPoints() {
		int n = this.getNbPoints();
		List<JNIISLPoint> res = new ArrayList<JNIISLPoint>(n);
		for (int i = 0; i < n; i++) {
			res.add(this.getPointAt(i));
		}
		return res;
	}

	public JNIISLMap lexFirstMap(int nbLoops) {
		int n = (int) this.getNDim() - nbLoops;
		JNIISLMap m = JNIISLMap.fromDomainAndRange(
				JNIISLSet.buildUniverseLike(this.copy()), this.copy());
		JNIISLBasicMap bm = JNIISLBasicMap.buildUniverse(m.getSpace());
		for (int i = 0; i < n; i++) {
			JNIISLConstraint c = JNIISLConstraint.buildEquality(JNIISLLocalSpace
					.fromSpace(m.getSpace()));
			c = c.setCoefficient(JNIISLDimType.isl_dim_in, i, 1);
			c = c.setCoefficient(JNIISLDimType.isl_dim_out, i, -1);
			bm = bm.addConstraint(c);
		}
		JNIISLMap ma = bm.toMap();
		m = m.intersect(ma).lexMin();
		//m = m.projectOut(JNIISLDimType.isl_dim_out, 0, n);
		return m;
	}


	/**
	 * keeps only one given dimension (pos) of the given dimension type
	 * 
	 * @param type
	 * @param pos
	 * @return
	 */
	public JNIISLSet projectIn(JNIISLDimType type, int pos) {
		int nbdims = (int) this.getSpace().getNbDims(type);
		if (pos < 0 || pos >= nbdims)
			throw new IllegalArgumentException();
		JNIISLSet res = this;
		if (pos + 1 <= nbdims - 1)
			res = res.projectOut(type, pos + 1, nbdims - pos - 1);
		if (pos - 1 >= 0)
			res = res.projectOut(type, 0, pos);
		
		return res;
	}
	/*** PROTECTED REGION END ***/


	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	/**
	 * isl_set_read_from_str 
	 * 
	 * @generated
	**/
	 public static JNIISLSet buildFromString(JNIISLContext ctx, String str) { 
		/*** PROTECTED REGION ID(static_isl_set_read_from_str) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLSet.build(ISLNative.isl_set_read_from_str(getNativePtr(ctx), str));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_empty 
	 * 
	@take space
	 * @generated
	**/
	 public static JNIISLSet buildEmpty(JNIISLSpace space) { 
		/*** PROTECTED REGION ID(static_isl_set_empty) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(space);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_empty(getNativePtr(space)));
			} finally {
				taken(space);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_universe 
	 * 
	@take space
	 * @generated
	**/
	 public static JNIISLSet buildUniverse(JNIISLSpace space) { 
		/*** PROTECTED REGION ID(static_isl_set_universe) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(space);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_universe(getNativePtr(space)));
			} finally {
				taken(space);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_nat_universe 
	 * 
	@take space
	 * @generated
	**/
	 public static JNIISLSet buildNonNegUniverse(JNIISLSpace space) { 
		/*** PROTECTED REGION ID(static_isl_set_nat_universe) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(space);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_nat_universe(getNativePtr(space)));
			} finally {
				taken(space);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_to_string 
	 * 
	 * @generated
	**/
	 public static String _toString(JNIISLSet set, int format) { 
		/*** PROTECTED REGION ID(static_isl_set_to_string) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_to_string(getNativePtr(set), format);
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * isl_union_set_from_set 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLUnionSet toUnionSet() {
		/*** PROTECTED REGION ID(isl_union_set_from_set) DISABLED START ***/
		JNIISLUnionSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLUnionSet.build(ISLNative.isl_union_set_from_set(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_from_params 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet toSetFromParamSet() {
		/*** PROTECTED REGION ID(isl_set_from_params) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_from_params(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_pw_multi_aff_from_set 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLPWMultiAff toPWMultiAff() {
		/*** PROTECTED REGION ID(isl_pw_multi_aff_from_set) DISABLED START ***/
		JNIISLPWMultiAff res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLPWMultiAff.build(ISLNative.isl_pw_multi_aff_from_set(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_list_from_set 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSetList toList() {
		/*** PROTECTED REGION ID(isl_set_list_from_set) DISABLED START ***/
		JNIISLSetList res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSetList.build(ISLNative.isl_set_list_from_set(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_ctx 
	 * 
	 * @generated
	**/
	public JNIISLContext getContext() {
		/*** PROTECTED REGION ID(isl_set_get_ctx) DISABLED START ***/
		JNIISLContext res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLContext.build(ISLNative.isl_set_get_ctx(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_space 
	 * 
	 * @generated
	**/
	public JNIISLSpace getSpace() {
		/*** PROTECTED REGION ID(isl_set_get_space) DISABLED START ***/
		JNIISLSpace res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLSpace.build(ISLNative.isl_set_get_space(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_copy 
	 * 
	 * @generated
	**/
	public JNIISLSet copy() {
		/*** PROTECTED REGION ID(isl_set_copy) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLSet.build(ISLNative.isl_set_copy(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_free 
	 * 
	 * @take this
	 * @generated
	**/
	public void free() {
		/*** PROTECTED REGION ID(isl_set_free) DISABLED START ***/
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				ISLNative.isl_set_free(getNativePtr(this));
			} finally {
				taken(this);
			}
		}
		
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_add_constraint 
	 * 
	 * @take this constraint
	 * @generated
	**/
	public JNIISLSet addConstraint(JNIISLConstraint constraint) {
		/*** PROTECTED REGION ID(isl_set_add_constraint) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, constraint);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_add_constraint(getNativePtr(this), getNativePtr(constraint)));
			} finally {
				taken(this);
				taken(constraint);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_n_basic_set 
	 * 
	 * @generated
	**/
	public int getNbBasicSets() {
		/*** PROTECTED REGION ID(isl_set_n_basic_set) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_n_basic_set(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_make_disjoint 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet makeDisjoint() {
		/*** PROTECTED REGION ID(isl_set_make_disjoint) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_make_disjoint(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_compute_divs 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet computeDivs() {
		/*** PROTECTED REGION ID(isl_set_compute_divs) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_compute_divs(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_remove_divs 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet removeDivs() {
		/*** PROTECTED REGION ID(isl_set_remove_divs) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_remove_divs(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_remove_unknown_divs 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet removeUnknownDivs() {
		/*** PROTECTED REGION ID(isl_set_remove_unknown_divs) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_remove_unknown_divs(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_remove_divs_involving_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet removeDivsInvolvingDims(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_set_remove_divs_involving_dims) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_remove_divs_involving_dims(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_dim 
	 * 
	 * @generated
	**/
	public int getNbDims(JNIISLDimType type) {
		/*** PROTECTED REGION ID(isl_set_dim) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_dim(getNativePtr(this), type.getValue());
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_tuple_name 
	 * 
	 * @generated
	**/
	public String getTupleName() {
		/*** PROTECTED REGION ID(isl_set_get_tuple_name) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_get_tuple_name(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_set_tuple_name 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet setTupleName(String s) {
		/*** PROTECTED REGION ID(isl_set_set_tuple_name) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_set_tuple_name(getNativePtr(this), s));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_dim_name 
	 * 
	 * @generated
	**/
	public String getDimName(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_get_dim_name) DISABLED START ***/
		String res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_get_dim_name(getNativePtr(this), type.getValue(), pos);
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_set_dim_name 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet setDimName(JNIISLDimType type, int pos, String s) {
		/*** PROTECTED REGION ID(isl_set_set_dim_name) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_set_dim_name(getNativePtr(this), type.getValue(), pos, s));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_has_tuple_name 
	 * 
	 * @generated
	**/
	public boolean hasTupleName() {
		/*** PROTECTED REGION ID(isl_set_has_tuple_name) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_has_tuple_name(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_has_dim_name 
	 * 
	 * @generated
	**/
	public boolean hasDimName(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_has_dim_name) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_has_dim_name(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_find_dim_by_name 
	 * 
	 * @generated
	**/
	public int findDimByName(JNIISLDimType type, String name) {
		/*** PROTECTED REGION ID(isl_set_find_dim_by_name) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_find_dim_by_name(getNativePtr(this), type.getValue(), name);
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_involves_dims 
	 * 
	 * @generated
	**/
	public boolean involvesDims(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_set_involves_dims) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_involves_dims(getNativePtr(this), type.getValue(), first, n) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_tuple_id 
	 * 
	 * @generated
	**/
	public JNIISLIdentifier getTupleID() {
		/*** PROTECTED REGION ID(isl_set_get_tuple_id) DISABLED START ***/
		JNIISLIdentifier res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLIdentifier.build(ISLNative.isl_set_get_tuple_id(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_dim_id 
	 * 
	 * @generated
	**/
	public JNIISLIdentifier getDimID(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_get_dim_id) DISABLED START ***/
		JNIISLIdentifier res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLIdentifier.build(ISLNative.isl_set_get_dim_id(getNativePtr(this), type.getValue(), pos));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_has_tuple_id 
	 * 
	 * @generated
	**/
	public boolean hasTupleID() {
		/*** PROTECTED REGION ID(isl_set_has_tuple_id) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_has_tuple_id(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_has_dim_id 
	 * 
	 * @generated
	**/
	public boolean hasDimID(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_has_dim_id) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_has_dim_id(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_set_tuple_id 
	 * 
	 * @take this id
	 * @generated
	**/
	public JNIISLSet setTupleID(JNIISLIdentifier id) {
		/*** PROTECTED REGION ID(isl_set_set_tuple_id) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, id);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_set_tuple_id(getNativePtr(this), getNativePtr(id)));
			} finally {
				taken(this);
				taken(id);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_set_dim_id 
	 * 
	 * @take this id
	 * @generated
	**/
	public JNIISLSet setDimID(JNIISLDimType type, int pos, JNIISLIdentifier id) {
		/*** PROTECTED REGION ID(isl_set_set_dim_id) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, id);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_set_dim_id(getNativePtr(this), type.getValue(), pos, getNativePtr(id)));
			} finally {
				taken(this);
				taken(id);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_find_dim_by_id 
	 * 
	 * @generated
	**/
	public int findDimByID(JNIISLDimType type, JNIISLIdentifier id) {
		/*** PROTECTED REGION ID(isl_set_find_dim_by_id) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_find_dim_by_id(getNativePtr(this), type.getValue(), getNativePtr(id));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_reset_tuple_id 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet resetTupleID() {
		/*** PROTECTED REGION ID(isl_set_reset_tuple_id) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_reset_tuple_id(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_dim_has_upper_bound 
	 * 
	 * @generated
	**/
	public boolean hasUpperBound(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_dim_has_upper_bound) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_dim_has_upper_bound(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_dim_has_lower_bound 
	 * 
	 * @generated
	**/
	public boolean hasLowerBound(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_dim_has_lower_bound) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_dim_has_lower_bound(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_dim_has_any_upper_bound 
	 * 
	 * @generated
	**/
	public boolean hasAnyUpperBound(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_dim_has_any_upper_bound) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_dim_has_any_upper_bound(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_dim_has_any_lower_bound 
	 * 
	 * @generated
	**/
	public boolean hasAnyLowerBound(JNIISLDimType type, int pos) {
		/*** PROTECTED REGION ID(isl_set_dim_has_any_lower_bound) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_dim_has_any_lower_bound(getNativePtr(this), type.getValue(), pos) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_plain_is_empty 
	 * 
	 * @generated
	**/
	public boolean plainIsEmpty() {
		/*** PROTECTED REGION ID(isl_set_plain_is_empty) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_plain_is_empty(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_empty 
	 * 
	 * @generated
	**/
	public boolean isEmpty() {
		/*** PROTECTED REGION ID(isl_set_is_empty) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_empty(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_plain_is_universe 
	 * 
	 * @generated
	**/
	public boolean plainIsUniverse() {
		/*** PROTECTED REGION ID(isl_set_plain_is_universe) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_plain_is_universe(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_singleton 
	 * 
	 * @generated
	**/
	public boolean isSingleton() {
		/*** PROTECTED REGION ID(isl_set_is_singleton) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_singleton(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_params 
	 * 
	 * @generated
	**/
	public boolean isParamSet() {
		/*** PROTECTED REGION ID(isl_set_is_params) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_params(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_wrapping 
	 * 
	 * @generated
	**/
	public boolean isWrapping() {
		/*** PROTECTED REGION ID(isl_set_is_wrapping) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_wrapping(getNativePtr(this)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_sample_point 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLPoint samplePoint() {
		/*** PROTECTED REGION ID(isl_set_sample_point) DISABLED START ***/
		JNIISLPoint res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLPoint.build(ISLNative.isl_set_sample_point(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_plain_is_equal 
	 * 
	 * @generated
	**/
	public boolean plainIsEqual(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_plain_is_equal) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_plain_is_equal(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_equal 
	 * 
	 * @generated
	**/
	public boolean isEqual(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_is_equal) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_equal(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_plain_is_disjoint 
	 * 
	 * @generated
	**/
	public boolean plainIsDisjoint(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_plain_is_disjoint) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_plain_is_disjoint(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_disjoint 
	 * 
	 * @generated
	**/
	public boolean isDisjoint(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_is_disjoint) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_disjoint(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_subset 
	 * 
	 * @generated
	**/
	public boolean isSubset(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_is_subset) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_subset(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_is_strict_subset 
	 * 
	 * @generated
	**/
	public boolean isStrictSubset(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_is_strict_subset) DISABLED START ***/
		boolean res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_is_strict_subset(getNativePtr(this), getNativePtr(set2)) != 0;
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_params 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet paramSet() {
		/*** PROTECTED REGION ID(isl_set_params) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_params(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_complement 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet complement() {
		/*** PROTECTED REGION ID(isl_set_complement) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_complement(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_project_out 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet projectOut(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_set_project_out) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_project_out(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_eliminate 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet eliminate(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_set_eliminate) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_eliminate(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_fix_si 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet sliceFixed(JNIISLDimType type, int pos, int value) {
		/*** PROTECTED REGION ID(isl_set_fix_si) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_fix_si(getNativePtr(this), type.getValue(), pos, value));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_fix_val 
	 * 
	 * @take this v
	 * @generated
	**/
	public JNIISLSet sliceFixed(JNIISLDimType type, int pos, JNIISLVal v) {
		/*** PROTECTED REGION ID(isl_set_fix_val) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, v);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_fix_val(getNativePtr(this), type.getValue(), pos, getNativePtr(v)));
			} finally {
				taken(this);
				taken(v);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lower_bound_si 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet sliceLB(JNIISLDimType type, int pos, int value) {
		/*** PROTECTED REGION ID(isl_set_lower_bound_si) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_lower_bound_si(getNativePtr(this), type.getValue(), pos, value));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lower_bound_val 
	 * 
	 * @take this value
	 * @generated
	**/
	public JNIISLSet sliceLB(JNIISLDimType type, int pos, JNIISLVal value) {
		/*** PROTECTED REGION ID(isl_set_lower_bound_val) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, value);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_lower_bound_val(getNativePtr(this), type.getValue(), pos, getNativePtr(value)));
			} finally {
				taken(this);
				taken(value);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_upper_bound_si 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet sliceUB(JNIISLDimType type, int pos, int value) {
		/*** PROTECTED REGION ID(isl_set_upper_bound_si) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_upper_bound_si(getNativePtr(this), type.getValue(), pos, value));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_upper_bound_val 
	 * 
	 * @take this value
	 * @generated
	**/
	public JNIISLSet sliceUB(JNIISLDimType type, int pos, JNIISLVal value) {
		/*** PROTECTED REGION ID(isl_set_upper_bound_val) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, value);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_upper_bound_val(getNativePtr(this), type.getValue(), pos, getNativePtr(value)));
			} finally {
				taken(this);
				taken(value);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_equate 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet sliceEquate(JNIISLDimType type1, int pos1, JNIISLDimType type2, int pos2) {
		/*** PROTECTED REGION ID(isl_set_equate) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_equate(getNativePtr(this), type1.getValue(), pos1, type2.getValue(), pos2));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_identity 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLMap identity() {
		/*** PROTECTED REGION ID(isl_set_identity) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLMap.build(ISLNative.isl_set_identity(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_coalesce 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet coalesce() {
		/*** PROTECTED REGION ID(isl_set_coalesce) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_coalesce(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_detect_equalities 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet detectEqualities() {
		/*** PROTECTED REGION ID(isl_set_detect_equalities) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_detect_equalities(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_remove_redundancies 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet removeRedundancies() {
		/*** PROTECTED REGION ID(isl_set_remove_redundancies) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_remove_redundancies(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_convex_hull 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet convexHull() {
		/*** PROTECTED REGION ID(isl_set_convex_hull) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_convex_hull(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_affine_hull 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet affineHull() {
		/*** PROTECTED REGION ID(isl_set_affine_hull) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_affine_hull(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_polyhedral_hull 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet polyhedralHull() {
		/*** PROTECTED REGION ID(isl_set_polyhedral_hull) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_polyhedral_hull(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_simple_hull 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet simpleHull() {
		/*** PROTECTED REGION ID(isl_set_simple_hull) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_simple_hull(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_unshifted_simple_hull 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet unshiftedSimpleHull() {
		/*** PROTECTED REGION ID(isl_set_unshifted_simple_hull) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_unshifted_simple_hull(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_drop_constraints_involving_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet dropConstraintsInvolvingDims(JNIISLDimType type, int first, int n) {
		/*** PROTECTED REGION ID(isl_set_drop_constraints_involving_dims) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_drop_constraints_involving_dims(getNativePtr(this), type.getValue(), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_sample 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLBasicSet sample() {
		/*** PROTECTED REGION ID(isl_set_sample) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_sample(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_unwrap 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLMap unwrap() {
		/*** PROTECTED REGION ID(isl_set_unwrap) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLMap.build(ISLNative.isl_set_unwrap(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_flatten 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet flatten() {
		/*** PROTECTED REGION ID(isl_set_flatten) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_flatten(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_flatten_map 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLMap flattenAsMap() {
		/*** PROTECTED REGION ID(isl_set_flatten_map) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLMap.build(ISLNative.isl_set_flatten_map(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lift 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet lift() {
		/*** PROTECTED REGION ID(isl_set_lift) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_lift(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_align_params 
	 * 
	 * @take this model
	 * @generated
	**/
	public JNIISLSet alignParams(JNIISLSpace model) {
		/*** PROTECTED REGION ID(isl_set_align_params) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, model);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_align_params(getNativePtr(this), getNativePtr(model)));
			} finally {
				taken(this);
				taken(model);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_add_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet addDims(JNIISLDimType type, int n) {
		/*** PROTECTED REGION ID(isl_set_add_dims) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_add_dims(getNativePtr(this), type.getValue(), n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_insert_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet insertDims(JNIISLDimType type, int pos, int n) {
		/*** PROTECTED REGION ID(isl_set_insert_dims) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_insert_dims(getNativePtr(this), type.getValue(), pos, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_move_dims 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet moveDims(JNIISLDimType dst_type, int dst_pos, JNIISLDimType src_type, int src_pos, int n) {
		/*** PROTECTED REGION ID(isl_set_move_dims) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_move_dims(getNativePtr(this), dst_type.getValue(), dst_pos, src_type.getValue(), src_pos, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_intersect_params 
	 * 
	 * @take this params
	 * @generated
	**/
	public JNIISLSet intersectParams(JNIISLSet params) {
		/*** PROTECTED REGION ID(isl_set_intersect_params) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, params);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_intersect_params(getNativePtr(this), getNativePtr(params)));
			} finally {
				taken(this);
				taken(params);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_intersect 
	 * 
	 * @take this set2
	 * @generated
	**/
	public JNIISLSet intersect(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_intersect) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, set2);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_intersect(getNativePtr(this), getNativePtr(set2)));
			} finally {
				taken(this);
				taken(set2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_union 
	 * 
	 * @take this set2
	 * @generated
	**/
	public JNIISLSet union(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_union) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, set2);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_union(getNativePtr(this), getNativePtr(set2)));
			} finally {
				taken(this);
				taken(set2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_subtract 
	 * 
	 * @take this set2
	 * @generated
	**/
	public JNIISLSet subtract(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_subtract) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, set2);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_subtract(getNativePtr(this), getNativePtr(set2)));
			} finally {
				taken(this);
				taken(set2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_apply 
	 * 
	 * @take this map
	 * @generated
	**/
	public JNIISLSet apply(JNIISLMap map) {
		/*** PROTECTED REGION ID(isl_set_apply) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, map);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_apply(getNativePtr(this), getNativePtr(map)));
			} finally {
				taken(this);
				taken(map);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_preimage_multi_aff 
	 * 
	 * @take this ma
	 * @generated
	**/
	public JNIISLSet preimage(JNIISLMultiAff ma) {
		/*** PROTECTED REGION ID(isl_set_preimage_multi_aff) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, ma);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_preimage_multi_aff(getNativePtr(this), getNativePtr(ma)));
			} finally {
				taken(this);
				taken(ma);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_preimage_pw_multi_aff 
	 * 
	 * @take this pma
	 * @generated
	**/
	public JNIISLSet preimage(JNIISLPWMultiAff pma) {
		/*** PROTECTED REGION ID(isl_set_preimage_pw_multi_aff) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, pma);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_preimage_pw_multi_aff(getNativePtr(this), getNativePtr(pma)));
			} finally {
				taken(this);
				taken(pma);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_preimage_multi_pw_aff 
	 * 
	 * @take this mpa
	 * @generated
	**/
	public JNIISLSet preimage(JNIISLMultiPWAff mpa) {
		/*** PROTECTED REGION ID(isl_set_preimage_multi_pw_aff) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, mpa);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_preimage_multi_pw_aff(getNativePtr(this), getNativePtr(mpa)));
			} finally {
				taken(this);
				taken(mpa);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_product 
	 * 
	 * @take this set2
	 * @generated
	**/
	public JNIISLSet product(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_product) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, set2);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_product(getNativePtr(this), getNativePtr(set2)));
			} finally {
				taken(this);
				taken(set2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_flat_product 
	 * 
	 * @take this set2
	 * @generated
	**/
	public JNIISLSet flatProduct(JNIISLSet set2) {
		/*** PROTECTED REGION ID(isl_set_flat_product) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, set2);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_flat_product(getNativePtr(this), getNativePtr(set2)));
			} finally {
				taken(this);
				taken(set2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_gist 
	 * 
	 * @take this context
	 * @generated
	**/
	public JNIISLSet gist(JNIISLSet context) {
		/*** PROTECTED REGION ID(isl_set_gist) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, context);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_gist(getNativePtr(this), getNativePtr(context)));
			} finally {
				taken(this);
				taken(context);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_gist_params 
	 * 
	 * @take this context
	 * @generated
	**/
	public JNIISLSet gistParams(JNIISLSet context) {
		/*** PROTECTED REGION ID(isl_set_gist_params) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, context);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_gist_params(getNativePtr(this), getNativePtr(context)));
			} finally {
				taken(this);
				taken(context);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_partial_lexmin 
	 * 
	 * @take this dom
	 * @generated
	**/
	public JNIISLSet partialLexMin(JNIISLSet dom) {
		/*** PROTECTED REGION ID(isl_set_partial_lexmin) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, dom);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_partial_lexmin(getNativePtr(this), getNativePtr(dom)));
			} finally {
				taken(this);
				taken(dom);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_partial_lexmax 
	 * 
	 * @take this dom
	 * @generated
	**/
	public JNIISLSet partialLexMax(JNIISLSet dom) {
		/*** PROTECTED REGION ID(isl_set_partial_lexmax) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this, dom);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_partial_lexmax(getNativePtr(this), getNativePtr(dom)));
			} finally {
				taken(this);
				taken(dom);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lexmin 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet lexMin() {
		/*** PROTECTED REGION ID(isl_set_lexmin) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_lexmin(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lexmax 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet lexMax() {
		/*** PROTECTED REGION ID(isl_set_lexmax) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.isl_set_lexmax(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lexmin_pw_multi_aff 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLPWMultiAff lexMinAsPWMultiAff() {
		/*** PROTECTED REGION ID(isl_set_lexmin_pw_multi_aff) DISABLED START ***/
		JNIISLPWMultiAff res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLPWMultiAff.build(ISLNative.isl_set_lexmin_pw_multi_aff(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_lexmax_pw_multi_aff 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLPWMultiAff lexMaxAsPWMultiAff() {
		/*** PROTECTED REGION ID(isl_set_lexmax_pw_multi_aff) DISABLED START ***/
		JNIISLPWMultiAff res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLPWMultiAff.build(ISLNative.isl_set_lexmax_pw_multi_aff(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_n_dim 
	 * 
	 * @generated
	**/
	public int getNbDims() {
		/*** PROTECTED REGION ID(isl_set_n_dim) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_n_dim(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_n_param 
	 * 
	 * @generated
	**/
	public int getNbParams() {
		/*** PROTECTED REGION ID(isl_set_n_param) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_n_param(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_basic_set_at 
	 * 
	 * @generated
	**/
	public JNIISLBasicSet getBasicSetAt(int pos) {
		/*** PROTECTED REGION ID(isl_set_get_basic_set_at) DISABLED START ***/
		JNIISLBasicSet res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLBasicSet.build(ISLNative.isl_set_get_basic_set_at(getNativePtr(this), pos));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_numberof_points 
	 * 
	 * @generated
	**/
	public int getNbPoints() {
		/*** PROTECTED REGION ID(isl_set_numberof_points) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_set_numberof_points(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_set_get_point_at 
	 * 
	 * @generated
	**/
	public JNIISLPoint getPointAt(int pos) {
		/*** PROTECTED REGION ID(isl_set_get_point_at) DISABLED START ***/
		JNIISLPoint res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLPoint.build(ISLNative.isl_set_get_point_at(getNativePtr(this), pos));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * lex_next 
	 * 
	 * @generated
	**/
	public JNIISLMap getLexNextMap(int nbInnerLoop) {
		/*** PROTECTED REGION ID(lex_next) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLMap.build(ISLNative.lex_next(getNativePtr(this), nbInnerLoop));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * lex_next_power 
	 * 
	 * @generated
	**/
	public JNIISLMap getLexNextPowerMap(int nbInnerLoop, int power) {
		/*** PROTECTED REGION ID(lex_next_power) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLMap.build(ISLNative.lex_next_power(getNativePtr(this), nbInnerLoop, power));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * lex_pred 
	 * 
	 * @generated
	**/
	public JNIISLMap getLexPredMap(int nbInnerLoop) {
		/*** PROTECTED REGION ID(lex_pred) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLMap.build(ISLNative.lex_pred(getNativePtr(this), nbInnerLoop));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * lex_pred_power 
	 * 
	 * @generated
	**/
	public JNIISLMap getLexPredPowerMap(int nbInnerLoop, int power) {
		/*** PROTECTED REGION ID(lex_pred_power) DISABLED START ***/
		JNIISLMap res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLMap.build(ISLNative.lex_pred_power(getNativePtr(this), nbInnerLoop, power));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * clear_tuple_name 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLSet clearTupleName() {
		/*** PROTECTED REGION ID(clear_tuple_name) DISABLED START ***/
		JNIISLSet res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLSet.build(ISLNative.clear_tuple_name(getNativePtr(this)));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLSet_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
