package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLUnionPWAffList_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLUnionPWAffList extends JNIObject {
	
	/* @generated */
	protected JNIISLUnionPWAffList(long ptr) {
		/*** PROTECTED REGION ID(ISLUnionPWAffList_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	/* @generated */
	protected static JNIISLUnionPWAffList build(long ptr) {
		return new JNIISLUnionPWAffList(ptr);
	}
	
	/*** PROTECTED REGION ID(ISLUnionPWAffList_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/


	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	/**
	 * isl_union_pw_aff_list_alloc 
	 * 
	 * @generated
	**/
	 public static JNIISLUnionPWAffList build(JNIISLContext ctx, int n) { 
		/*** PROTECTED REGION ID(static_isl_union_pw_aff_list_alloc) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_alloc(getNativePtr(ctx), n));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * isl_union_pw_aff_list_get_ctx 
	 * 
	 * @generated
	**/
	public JNIISLContext getContext() {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_get_ctx) DISABLED START ***/
		JNIISLContext res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLContext.build(ISLNative.isl_union_pw_aff_list_get_ctx(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_copy 
	 * 
	 * @generated
	**/
	public JNIISLUnionPWAffList copy() {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_copy) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_copy(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_free 
	 * 
	 * @take this
	 * @generated
	**/
	public void free() {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_free) DISABLED START ***/
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				ISLNative.isl_union_pw_aff_list_free(getNativePtr(this));
			} finally {
				taken(this);
			}
		}
		
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_n_union_pw_aff 
	 * 
	 * @generated
	**/
	public int getNbUnionPWAffs() {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_n_union_pw_aff) DISABLED START ***/
		int res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = ISLNative.isl_union_pw_aff_list_n_union_pw_aff(getNativePtr(this));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_get_union_pw_aff 
	 * 
	 * @generated
	**/
	public JNIISLUnionPWAffList get(int index) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_get_union_pw_aff) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_get_union_pw_aff(getNativePtr(this), index));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_set_union_pw_aff 
	 * 
	 * @take this pa
	 * @generated
	**/
	public JNIISLUnionPWAffList set(int index, JNIISLUnionPWAff pa) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_set_union_pw_aff) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters(this, pa);
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_set_union_pw_aff(getNativePtr(this), index, getNativePtr(pa)));
			} finally {
				taken(this);
				taken(pa);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_insert 
	 * 
	 * @take this el
	 * @generated
	**/
	public JNIISLUnionPWAffList insert(int pos, JNIISLUnionPWAff el) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_insert) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters(this, el);
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_insert(getNativePtr(this), pos, getNativePtr(el)));
			} finally {
				taken(this);
				taken(el);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_add 
	 * 
	 * @take this el
	 * @generated
	**/
	public JNIISLUnionPWAffList add(JNIISLUnionPWAff el) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_add) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters(this, el);
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_add(getNativePtr(this), getNativePtr(el)));
			} finally {
				taken(this);
				taken(el);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_drop 
	 * 
	 * @take this
	 * @generated
	**/
	public JNIISLUnionPWAffList drop(int first, int n) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_drop) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters(this);
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_drop(getNativePtr(this), first, n));
			} finally {
				taken(this);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	/**
	 * isl_union_pw_aff_list_concat 
	 * 
	 * @take this list2
	 * @generated
	**/
	public JNIISLUnionPWAffList concat(JNIISLUnionPWAffList list2) {
		/*** PROTECTED REGION ID(isl_union_pw_aff_list_concat) DISABLED START ***/
		JNIISLUnionPWAffList res;
		
		synchronized(LOCK) {
			checkParameters(this, list2);
			try {
				res = JNIISLUnionPWAffList.build(ISLNative.isl_union_pw_aff_list_concat(getNativePtr(this), getNativePtr(list2)));
			} finally {
				taken(this);
				taken(list2);
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLUnionPWAffList_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
