package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLStandardIO_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLStandardIO extends JNIObject {
	
	/* @generated */
	protected JNIISLStandardIO(long ptr) {
		/*** PROTECTED REGION ID(ISLStandardIO_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	/* @generated */
	protected static JNIISLStandardIO build(long ptr) {
		return new JNIISLStandardIO(ptr);
	}
	
	/*** PROTECTED REGION ID(ISLStandardIO_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/


	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLStandardIO_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
