package fr.irisa.cairn.jnimap.isl.jni;

import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import fr.irisa.cairn.jnimap.runtime.JNIObject;


/*** PROTECTED REGION ID(ISLASTBlockNode_userImport) ENABLED START ***/
	/*
		Put you custom import here ....
	*/
/*** PROTECTED REGION END ***/

/**
 *  Automatically generated by jnimap 
 * @generated
 */
public class JNIISLASTBlockNode extends JNIISLASTNode {
	
	
	/* @generated */
	protected JNIISLASTBlockNode(long ptr) {
		/*** PROTECTED REGION ID(ISLASTBlockNode_Constructor) DISABLED START ***/
		super(ptr);
		/*** PROTECTED REGION END ***/
	}
	
	
		public Object accept(IISLASTNodeVisitor visitor, Object arg) {
			return visitor.visitJNIISLASTBlockNode(this, arg);
		}
	
	
	/*** PROTECTED REGION ID(ISLASTBlockNode_userCode) ENABLED START ***/
	/*** PROTECTED REGION END ***/

	/*************************************** 
	 *	     Struct Field Accessors        * 
	 ***************************************/

	
	/*************************************** 
	 *	         Static Methods            * 
	 ***************************************/
	
	/*************************************** 
	 *	         Member Methods            * 
	 ***************************************/
	/**
	 * isl_ast_node_block_get_children 
	 * 
	 * @generated
	**/
	public JNIISLASTNodeList getChildren() {
		/*** PROTECTED REGION ID(isl_ast_node_block_get_children) DISABLED START ***/
		JNIISLASTNodeList res;
		
		synchronized(LOCK) {
			checkParameters();
			try {
				res = JNIISLASTNodeList.build(ISLNative.isl_ast_node_block_get_children(getNativePtr(this)));
			} finally {
			}
		}
		
		return res;
		/*** PROTECTED REGION END ***/
	}
	
	
	public String toString() {
		/*** PROTECTED REGION ID(ISLASTBlockNode_toString) DISABLED START ***/
			return ISLPrettyPrinter.asString(this);
		/*** PROTECTED REGION END ***/
	}
}
