/**/
affine wave_3d {TSTEPS,N,M,K| TSTEPS > 3 && N > 3 && M > 3 && K > 3}
input 
output
	double B {t,i,j,k|t == TSTEPS && 0<=i<N && 0<=j<M && 0<=k<K};
local 
	double temp_B {t,i,j|0<=i<N && 0<=j<M && 0<=k<K && 0<=t<TSTEPS};
let
	temp_B[t,i,j,k] = case
						{|t<=1 && 2<=i<N-2 && 2<=j<M-2 && 2<=k<=K-2} : 6.0*([i]+[j]+[k])/(N+M+K) - 1.0;
						{|t>1 && 2<=i<N-2 && 2<=j<M-2 && 2<=k<=K-2} : 1.98125*temp_B[t-1,i,j,k] - temp_B[t-2,i,j,k] + 0.00333*(temp_B[t-1,i+1,j,k]+temp_B[t-1,i-1,j,k]
													+temp_B[t-1,i,j+1,k]+temp_B[t-1,i,j-1,k]+temp_B[t-1,i,j,k-1]+temp_B[t-1,i,j,k+1])
													-0.00021*(temp_B[t-1,i+2,j,k]+temp_B[t-1,i-2,j,k]+temp_B[t-1,i,j+2,k]+temp_B[t-1,i,j-2,k]
													+temp_B[t-1,i,j,k+2]+temp_B[t-1,i,j,k+2]);
						{|0<=i<=1 } || {|0<=j<=1 } || {|0<=k<=1} || {|N-2<=i<=N-1 } || {|M-2<=j<=M-1 } || {|K-2<=k<=K-1}: 0.0;  
					esac; 

	B[t,i,j,k] = temp_B[t-1,i,j,k]; 
.
/**/
/*
affine wave_3d {TSTEPS,N,M,K| TSTEPS > 3 && N > 3 && M > 3 && K > 3}
input 
output
	double B {i,j,k|0<=i<N && 0<=j<M && 0<=k<K};
local 
	double temp_B {t,i,j|0<=i<N && 0<=j<M && 0<=k<K && 0<=t<TSTEPS};
let
	temp_B[t,i,j,k] = case
						{|t<=1 && 2<=i<N-2 && 2<=j<M-2 && 2<=k<=K-2} : 6.0*([i]+[j]+[k])/(N+M+K) - 1.0;
						{|t>1 && 2<=i<N-2 && 2<=j<M-2 && 2<=k<=K-2} : 1.98125*temp_B[t-1,i,j,k] - temp_B[t-2,i,j,k] + 0.00333*(temp_B[t-1,i+1,j,k]+temp_B[t-1,i-1,j,k]
													+temp_B[t-1,i,j+1,k]+temp_B[t-1,i,j-1,k]+temp_B[t-1,i,j,k-1]+temp_B[t-1,i,j,k+1])
													+0.00021*(temp_B[t-1,i+2,j,k]+temp_B[t-1,i-2,j,k]+temp_B[t-1,i,j+2,k]+temp_B[t-1,i,j-2,k]
													+temp_B[t-1,i,j,k+2]+temp_B[t-1,i,j,k+2]);
						{|0<=i<=1 } || {|0<=j<=1 } || {|0<=k<=1} || {|N-2<=i<=N-1 } || {|M-2<=j<=M-1 } || {|K-2<=k<=K-1}: 0.0;  
					esac; 

	B[t,i,j,k] = temp_B[TSTEPS-1,i,j,k]; 
.
*/