//3 Matrix Multiplications (E=A.B; F=C.D; G=E.F)
affine 3mm {P,Q,R,S,T|(P,Q,R,S,T)>0}
	input
		double A{i,j|0<=i<P && 0<=j<Q};
		double B{i,j|0<=i<Q && 0<=j<R};
		double C{i,j|0<=i<R && 0<=j<S};
		double D{i,j|0<=i<S && 0<=j<T};
	output
		double G{i,j|0<=i<P && 0<=j<T};
	local
		double E{i,j|0<=i<P && 0<=j<R};
		double F{i,j|0<=i<R && 0<=j<T};
	let
		E[i,j] = reduce(+, [k], A[i,k] * B[k,j]);
		F[i,j] = reduce(+, [k], C[i,k] * D[k,j]);
		G[i,j] = reduce(+, [k], E[i,k] * F[k,j]);
. 