affine BlockMM {n, b| (n,b)>0}
given
	float A, B {ii,jj,i,j | 0<= (ii,jj)<n && 0<=(i,j)<b};
returns
	float C {ii,jj,i,j | 0<= (ii,jj)<n && 0<=(i,j)<b};
using 
	float CC {ii,jj,kk,i,j | 0<= (ii,jj,kk)<n && 0<=(i,j)<b};
through
use {ii, jj, kk | 0<=(ii,jj,kk)<n} MM[b] ((ii,jj,kk,i,j->ii,kk,i,j)@A,
		(ii,jj,kk,i,j->kk,jj,i,j)@B) returns (CC);
   C[ii,jj,i,j] = reduce(+, (ii,jj,kk,i,j->ii,jj,i,j), CC);
.


affine MM {N| N>0}
given
	float A, B {i,j | 0<= (i,j)<N};
returns
	float C {i,j | 0<=(i,j) <N};
using // No local variables
through
   C[i,j]      = reduce(+, [k], A[i,k]*B[k,j]);
.