name: build

on:
  pull_request:
    types: [synchronize]

jobs:

  build-plugin:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: test-pr-${{ github.event.number }}
      url: ${{ steps.deployment.outputs.page_url }}test-pr-${{ github.event.number }}

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: build alphaz
      run: mvn clean package

    - name: make update-site readme
      run: |
        echo "#1" > ./releng/alphaz.update/target/repository/README.md
        echo "#2" > ./releng/alphaz.update/target/repository/test-pr-${{ github.event.number }}/README.md
        
 
    - name: build update-site
      uses: actions/jekyll-build-pages@v1
      with:
        source: "./releng/alphaz.update/target/repository"
        destination: "./update-site"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./update-site"

    - name: deploy update-site
      id: deployment
      uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action



