name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up java (jdk-8)
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: build alphaz
      run: mvn clean package

    - name: make update-site readme
      run: ./scripts/make-update-site-readme.sh
    
    - name: build update-site
      uses: actions/jekyll-build-pages@v1
      with:
        source: "./releng/alphaz.update/target/repository"
        destination: "./update-site"

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: "./update-site"
    
  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest

    steps:
      - name: deploy update-site
        id: deployment
        uses: actions/deploy-pages@v2 # or the latest "vX.X.X" version tag for this action
